name: connect

on: [push, workflow_dispatch]

jobs:
  test-iranian-hosts:
    runs-on: ubuntu-latest
    
    steps:
    - name: dns resolve
      run: |
        dig short+ www.arvancloud.ir
        echo ""
        dig short+ runflare.com
    - name: Test HTTP/HTTPS Connectivity
      run: |
        
        echo "Testing arvancloud.ir:"
        curl -v -L -m 10 https://www.arvancloud.ir 2>&1 | head -20
        echo "Testing runflare.com:"
        curl -v -L -m 10 https://runflare.com 2>&1 | head -20
    
    - name: Test HTTP/HTTPS ports connectivity
      run: |
        echo "testing 443/80 for runflare.com"
        timeout 5 echo > /dev/tcp/runflare.com/443
        timeout 5 echo > /dev/tcp/runflare.com/80
        echo "testing the same for arvanshit"
        timeout 5 echo > /dev/tcp/www.arvancloud.ir/443
        timeout 5 echo > /dev/tcp/www.arvancloud.ir/80
